Elka/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Elka/Pages/Courses/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elka.Core;
using Elka.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages.Courses
{
    public class DeleteModel : PageModel
    {
        private readonly ICourseData _courseData;
        public Course Course { get; set; }

        public DeleteModel(ICourseData courseData)
        {
            _courseData = courseData;
        }

        public IActionResult OnGet(int courseId)
        {
            Course = _courseData.GetById(courseId);

            if (Course == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }

        public IActionResult OnPost(int courseId)
        {
            var course = _courseData.Delete(courseId);
            _courseData.Commit();

            if (course == null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{course.Name} deleted";

            return RedirectToPage("./List");
        }
    }
}

Elka/Pages/Courses/Detail.cshtml.cs
using Elka.Core;
using Elka.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages.Courses
{
    public class DetailModel : PageModel
    {
        private readonly ICourseData _courseData;
        public Course Course { get; set; }

        [TempData]
        public string Message { get; set; }

        public DetailModel(ICourseData courseData)
        {
            _courseData = courseData;
        }

        public IActionResult OnGet(int courseId)
        {
            Course = _courseData.GetById(courseId);

            if (Course == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }
    }
}

Elka/Pages/Courses/Details.cshtml.cs
using Elka.Core;
using Elka.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages.Courses
{
    public class DetailsModel : PageModel
    {
        private readonly ICourseData _courseData;
        public Course Course { get; set; }

        [TempData]
        public string Message { get; set; }

        public DetailsModel(ICourseData courseData)
        {
            _courseData = courseData;
        }

        public IActionResult OnGet(int courseId)
        {
            Course = _courseData.GetById(courseId);

            if (Course == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }
    }
}

Elka/Pages/Courses/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elka.Core;
using Elka.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages.Courses
{
    public class EditModel : PageModel
    {
        private readonly ICourseData _courseData;

        [BindProperty]
        public Course Course { get; set; }

        public EditModel(ICourseData courseData)
        {
            _courseData = courseData;
        }

        public IActionResult OnGet(int? courseId)
        {
            if (courseId.HasValue)
            {
                Course = _courseData.GetById(courseId.Value);
            }
            else
            {
                Course = new Course {Teacher = new Teacher()};
            }
            
            if (Course == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Course.Id > 0)
            {
                _courseData.Update(Course);
                TempData["Message"] = "Course updated";
            }
            else
            {
                _courseData.Add(Course);
                TempData["Message"] = "Course created";
            }
            _courseData.Commit();

            return RedirectToPage("./Details", new {courseId = Course.Id});
        }
    }
}

Elka/Pages/Courses/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elka.Core;
using Elka.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages.Courses
{
    public class ListModel : PageModel
    {
        private readonly ICourseData _courseData;
        public IEnumerable<Course> Courses { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        [BindProperty(SupportsGet = true)]
        public int SearchChoice { get; set; }

        public ListModel(ICourseData courseData)
        {
            _courseData = courseData;
        }

        public void OnGet()
        {
            switch (SearchChoice)
            {
                default:
                    Courses = _courseData.GetCoursesByName(SearchTerm);
                    break;
                case 1:
                    Courses = _courseData.GetCoursesByMoniker(SearchTerm);
                    break;
                case 2:
                    Courses = _courseData.GetCoursesByEcts(SearchTerm);
                    break;
                case 3:
                    Courses = _courseData.GetCoursesByTeacherFirstName(SearchTerm);
                    break;
                case 4:
                    Courses = _courseData.GetCoursesByTeacherLastName(SearchTerm);
                    break;
            }
        }
    }
}

Elka/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Elka/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Elka/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elka.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Elka/Pages/ViewComponents/CourseCountViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elka.Data;
using Microsoft.AspNetCore.Mvc;

namespace Elka.Pages.ViewComponents
{
    public class CourseCountViewComponent
        : ViewComponent
    {
        private readonly ICourseData _courseData;

        public CourseCountViewComponent(ICourseData courseData)
        {
            _courseData = courseData;
        }

        public IViewComponentResult Invoke()
        {
            var count = _courseData.GetCountOfCourse();

            return View(count);
        }
    }
}

Elka/Pages/Contact.cshtml
@page
@model Elka.Pages.ContactModel
@{
	ViewData["Title"] = "Contact";
}

<h1>Contact</h1>

<span style="font-size: 48px">
	<a href="mailto:kuba.kamoda@gmail.com"><i class="far fa-envelope" style="color: #000000;"></i></a>
	<span style="font-size: 20px; color: black">
		<a href="mailto:kuba.kamoda@gmail.com" style="color: black">kuba.kamoda at gmail.com</a>
	</span>
</span>

<br />

<span style="font-size: 48px">
	<a href="https://github.com/kubkam"><i class="fab fa-github" style="color: #000000;"></i></a>
	<span style="font-size: 20px; color: black">
		<a href="https://github.com/kubkam" style="color: black">github.com/kubkam</a>
	</span>
</span>

<br />

<span style="font-size: 48px">
	<a href="https://https://linkedin.com/in/kuba-kamoda/"><i class="fab fa-linkedin" style="color: #1e90ff;"></i></a>
	<span style="font-size: 20px; color: black">
		<a href="https://linkedin.com/in/kuba-kamoda/" style="color: black">linkedin.com/in/kuba-kamoda</a>
	</span>
</span>

@section Scripts
	{
	<environment include="Development">
		<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
		<link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css" />
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/fontawesome.css" />
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/js/all.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/js/fontawesome.js"></script>
	</environment>
}

Elka/Pages/Courses/Delete.cshtml
@page "{courseId:int}"
@model Elka.Pages.Courses.DeleteModel
@{
	ViewData["Title"] = "Delete";
}

<h2>Deleting @Model.Course.Name</h2>
<div class="alert alert-danger">
	Are you sure you want to delete @Model.Course.Name?
</div>
@{ 
	<partial name="_Detail" model="Model.Course" />
}

<form method="post">
	<button type="submit" class="btn btn-danger">Yes!</button>
	<a asp-page="List" class="btn btn-light">Cancel</a>
</form>

Elka/Pages/Courses/Details.cshtml
@page "{courseId:int}"

@model Elka.Pages.Courses.DetailsModel
@{
	ViewData["Title"] = "Detail";
}

<h2>@Model.Course.Name</h2>

@if (Model.Message != null)
{
	<div class="alert alert-info">@Model.Message</div>
}

@{
	<partial name="_Detail" model="@Model.Course"/>
}
<br>

<a asp-page="./List" class="btn btn-info">Back to list</a>
<a asp-page="./Edit" class="btn btn-light" asp-route-courseid="@Model.Course.Id">Edit this course</a>
<a asp-page="./Delete" class="btn btn-danger" asp-route-courseid="@Model.Course.Id">Delete</a>

Elka/Pages/Courses/Edit.cshtml
@page "{courseId:int?}"
@using Elka.Core
@model Elka.Pages.Courses.EditModel
@{
	if (Model.Course.Id > 0)
	{
		ViewData["Title"] = "Edit";
	}
	else
	{
		ViewData["Title"] = "Create";
	}
}

@if (Model.Course.Id > 0)
{
	<h2>Editing @Model.Course.Name</h2>
}
else
{
	<h2>Creating new Course</h2>
}

<form method="post">
	<input type="hidden" asp-for="Course.Id" />
	<div class="form-group">
		<label asp-for="Course.Name">Course's Name</label>
		<input asp-for="Course.Name" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.Name"></span>
	</div>
	<div class="form-group">
		<label asp-for="Course.Moniker">Course's Moniker</label>
		<input asp-for="Course.Moniker" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.Moniker"></span>
	</div>
	<div class="form-group">
		<label asp-for="Course.ECTS"></label>
		<input asp-for="Course.ECTS" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.ECTS"></span>
	</div>
	<div class="form-group">
		<label asp-for="Course.HowEasy">How easy is this course?</label>
		<input asp-for="Course.HowEasy" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.HowEasy"></span>
	</div>
	<div class="form-group">
		<label asp-for="Course.InterestingLevel">How interesting is this course?</label>
		<input asp-for="Course.InterestingLevel" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.InterestingLevel"></span>
	</div>

	<input type="hidden" asp-for="Course.Teacher.Id" />
	<div class="form-group">
		<label asp-for="Course.Teacher.FirstName">Teacher's first name</label>
		<input asp-for="Course.Teacher.FirstName" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.Teacher.FirstName"></span>
	</div>
	<div class="form-group">
		<label asp-for="Course.Teacher.LastName">Teacher's last name</label>
		<input asp-for="Course.Teacher.LastName" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.Teacher.LastName"></span>
	</div>
	<div class="form-group">
		<label asp-for="Course.Descriptions">Description</label>
		<input asp-for="Course.Descriptions" class="form-control" />
		<span class="text-danger" asp-validation-for="Course.Descriptions"></span>
	</div>

	<button type="submit" class="btn btn-primary" asp-route-courseid="@Model.Course.Id">Save</button>

	<a asp-page="./List" class="btn btn-secondary">Cancel</a>

</form>

@section Scripts {
	<partial name="Shared/_ValidationScriptsPartial"/>
}

Elka/Pages/Courses/List.cshtml
@page
@model Elka.Pages.Courses.ListModel
@{
	ViewData["Title"] = "Courses";
}

<p>
	<h1>Courses List</h1>
	<a asp-page="./Edit" class="btn btn-link">Create New Course</a>
</p>

<form method="get">
	<div class="form-group">
		<div class="input-group">
			<input type="search" class="form-control" placeholder="Search" asp-for="SearchTerm" />
			<select class="custom-select font-weight-bold" id="inputGroupSelect04" asp-for="SearchChoice">
				<option value="0" selected>Course's Name</option>
				<option value="1">Course's Moniker</option>
				<option value="2">ECTS (please enter a number from 0 to 5)</option>
				<option value="3">Teacher's first name</option>
				<option value="4">Teacher's last name</option>
			</select>
			<div class="input-group-append">
				<button class="btn btn-outline-secondary">Search</button>
			</div>
		</div>
	</div>
</form>

<table id="course" class="table table-striped table-bordered display" style="width:100%">
	<thead>
		<tr>
			<th>
				Name
			</th>
			<th>
				Moniker
			</th>
			<th>
				ECTS
			</th>
			<th>
				Teacher First Name
			</th>
			<th>
				Teacher Last Name
			</th>
			<th>
				How easy
			</th>
			<th>
				Interesting level
			</th>
			<th>
				Action
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var course in Model.Courses)
		{
			<partial name="_Summary" model="course" />
		}
	</tbody>
</table>

<a asp-page="./Edit" class="btn btn-secondary">Add new Course</a>
@if (Model.SearchTerm != null)
{
	<a asp-page="./List" class="btn btn-warning">Remove all filters</a>
}

@section Scripts
{
	<environment include="Development">
		<script src="~/lib/datatables/js/jquery.dataTables.js"></script>
		<script src="~/lib/datatables/js/dataTables.bootstrap4.js"></script>
		<link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/w/bs4/dt-1.10.18/datatables.min.css"/>
		<script type="text/javascript" src="https://cdn.datatables.net/w/bs4/dt-1.10.18/datatables.min.js"></script>
	</environment>

	<script>
		$(document).ready(function() {
			$('#course').DataTable({
				processing: true,
				"searching": false,
				"scrollX": true
			});
			}
		);

	</script>
}

Elka/Pages/Courses/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>Your course was not found</h1>

<a asp-page="./List" class="btn btn-primary">See all Courses</a>

Elka/Pages/Courses/_Detail.cshtml
@using Elka.Core
@model Course

<div>
	<b>Moniker:</b>  @Model.Moniker
</div>
<div>
	<b>ECTS:</b>  @Model.ECTS
</div>
<div>
	<b>Teacher:</b>  @Model.Teacher.FirstName @Model.Teacher.LastName
</div>
<div>
	<b>How easy:</b>  @Model.HowEasy
</div>
<div>
	<b>Interesting level:</b>  @Model.InterestingLevel
</div>
<div>
	<b>Descriptions:</b>  @Model.Descriptions
</div>

Elka/Pages/Courses/_Summary.cshtml
@using Elka.Core
@model Course


<tr>
	<td>
		@Model.Name
	</td>
	<td>
		@Model.Moniker
	</td>
	<td>
		@Model.ECTS
	</td>
	<td>
		@Model.Teacher.FirstName
	<td>
		@Model.Teacher.LastName
	</td>
	<td>
		@Model.HowEasy
	</td>
	<td>
		@Model.InterestingLevel
	</td>
	<td>
		<a asp-page="./Edit" asp-route-courseid="@Model.Id">Edit</a> |
		<a asp-page="./Details" asp-route-courseid="@Model.Id">Details</a> |
		<a asp-page="./Delete" asp-route-courseid="@Model.Id">Delete</a>
	</td>
</tr>

Elka/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
	<h1 class="display-4"><b>Welcome</b></h1>
	<p style="font-size: 20px">
		Elka is a simple CRUD web application for browsing courses which you attend at your university or school.
		<br/>
		What you need is add new course on website and then easily browse through them.
		<br/>
		I'm using <a href="https://datatables.net/">DataTables</a> for formatting courses as a table.
		<br/>
		Check my other projects on my <a href="https://github.com/kubkam">GitHub</a>. Go to <a asp-page="Contact">Contact</a> page and check contact possibilities.
	</p>

	<vc:course-count></vc:course-count>
</div>

Elka/Pages/Shared/Components/CourseCount/Default.cshtml
@model int

<div class="card card-body bg-light">

	<b>
		There are @Model courses here.
		<a asp-page="/Courses/List">See them all</a>
	</b>
</div>

Elka/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Elka</title>

    <environment include="Development">
	    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Elka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-page="/Courses/List">Courses</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-page="/Contact">Contact</a>
	                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Elka - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>